name:                headlinecli
version:             0.1.0.0
github:              "soerenberg/headline-cli"
license:             MIT
author:              "Sören Lennart Berg"
maintainer:          "soeren.berg@protonmail.com"
copyright:           "2021 Sören Lennart Berg"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/soerenberg/headline-cli#readme>

dependencies:
- base >= 4.7 && < 5
- scalpel >= 0.6 && < 1
- process >= 1.6.9 && < 2

executables:
  headlinecli-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
